chore: remove because unmaintained
error: 'light' has been removed because it was unmaintained. 'brightnessctl' and 'acpilight' provide similar functionality.